// Shared transcription-language list, sourced once so the Settings panel and the
// onboarding flow present the same searchable options (issue #9: Settings used a
// free-text input, onboarding a short curated Select — both now use a Combobox
// over this list). `auto` (automatic language detection) leads; the rest are the
// common Whisper/Parakeet language hints, labelled "Name (code)" so a search
// matches either the English name or the ISO code.
export interface TranscriptionLanguageOption {
  value: string;
  label: string;
}

export const TRANSCRIPTION_LANGUAGE_OPTIONS: TranscriptionLanguageOption[] = [
  { value: "auto", label: "Auto-detect" },
  { value: "en", label: "English (en)" },
  { value: "zh", label: "Chinese (zh)" },
  { value: "de", label: "German (de)" },
  { value: "es", label: "Spanish (es)" },
  { value: "ru", label: "Russian (ru)" },
  { value: "ko", label: "Korean (ko)" },
  { value: "fr", label: "French (fr)" },
  { value: "ja", label: "Japanese (ja)" },
  { value: "pt", label: "Portuguese (pt)" },
  { value: "tr", label: "Turkish (tr)" },
  { value: "pl", label: "Polish (pl)" },
  { value: "ca", label: "Catalan (ca)" },
  { value: "nl", label: "Dutch (nl)" },
  { value: "ar", label: "Arabic (ar)" },
  { value: "sv", label: "Swedish (sv)" },
  { value: "it", label: "Italian (it)" },
  { value: "id", label: "Indonesian (id)" },
  { value: "hi", label: "Hindi (hi)" },
  { value: "fi", label: "Finnish (fi)" },
  { value: "vi", label: "Vietnamese (vi)" },
  { value: "he", label: "Hebrew (he)" },
  { value: "uk", label: "Ukrainian (uk)" },
  { value: "el", label: "Greek (el)" },
  { value: "ms", label: "Malay (ms)" },
  { value: "cs", label: "Czech (cs)" },
  { value: "ro", label: "Romanian (ro)" },
  { value: "da", label: "Danish (da)" },
  { value: "hu", label: "Hungarian (hu)" },
  { value: "ta", label: "Tamil (ta)" },
  { value: "no", label: "Norwegian (no)" },
  { value: "th", label: "Thai (th)" },
  { value: "ur", label: "Urdu (ur)" },
  { value: "hr", label: "Croatian (hr)" },
  { value: "bg", label: "Bulgarian (bg)" },
  { value: "lt", label: "Lithuanian (lt)" },
  { value: "la", label: "Latin (la)" },
  { value: "mi", label: "Maori (mi)" },
  { value: "ml", label: "Malayalam (ml)" },
  { value: "cy", label: "Welsh (cy)" },
  { value: "sk", label: "Slovak (sk)" },
  { value: "te", label: "Telugu (te)" },
  { value: "fa", label: "Persian (fa)" },
  { value: "lv", label: "Latvian (lv)" },
  { value: "bn", label: "Bengali (bn)" },
  { value: "sr", label: "Serbian (sr)" },
  { value: "az", label: "Azerbaijani (az)" },
  { value: "sl", label: "Slovenian (sl)" },
  { value: "kn", label: "Kannada (kn)" },
  { value: "et", label: "Estonian (et)" },
  { value: "mk", label: "Macedonian (mk)" },
  { value: "eu", label: "Basque (eu)" },
  { value: "is", label: "Icelandic (is)" },
  { value: "hy", label: "Armenian (hy)" },
  { value: "ne", label: "Nepali (ne)" },
  { value: "sw", label: "Swahili (sw)" },
  { value: "gl", label: "Galician (gl)" },
  { value: "mr", label: "Marathi (mr)" },
  { value: "pa", label: "Punjabi (pa)" },
  { value: "si", label: "Sinhala (si)" },
  { value: "km", label: "Khmer (km)" },
  { value: "sq", label: "Albanian (sq)" },
  { value: "af", label: "Afrikaans (af)" },
  { value: "ka", label: "Georgian (ka)" },
  { value: "be", label: "Belarusian (be)" },
];
